import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import { I18nextProvider } from 'react-i18next';
// import './i18n';
import i18next from 'i18next';

const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Duolingo - The world's best way to learn a language",
  description: 'Generated by create next app',
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      {/* <I18nextProvider i18n={i18next}> */}
        <html lang='en'>
          <body className={font.className}>{children}</body>
        </html>
      {/* </I18nextProvider> */}
    </ClerkProvider>
  );
}

export default RootLayout;
